### ISSUE TITLE
Package Repository Referenced as pc_repo not pe_repo

### ISSUE THREAD

**Issue by smbambling** [puppetlabs/puppetlabs-puppet_agent#105]
Not sure if this is a bug or a feature, but the repositories are referenced as pc_repo in place of pe_repo. Which are configured when installing via the curl command provided via the console.

If this is a feature, is there a reason why its named pc_repo ?  Also is there future planing to remove the pe_repo on agents that already were installed in another method ?

**Comment by MikaelSmith** [comment]
The naming is based on [Puppet Collections](https://puppet.com/blog/welcome-to-puppet-collections). However, since PE installs use repos hosted on a designated pe_repo server, it would make sense to keep the pe_repo name to differentiate between them and repositories pointing to yum.puppetlabs.com or apt.puppetlabs.com.

I've filed [MODULES-3250](https://tickets.puppetlabs.com/browse/MODULES-3250) to track that.

I've considered some way to do cleanup, but in general I don't think this module should prescribe too many removed resources; that makes it challenging to manage them later if some reason comes up.
