### ISSUE TITLE
service puppet not managed on PE 2016.1.2

### ISSUE THREAD

**Issue by Raskil** [puppetlabs/puppetlabs-puppet_agent#145]
Hi,

we face a problem with the pupept_agent module and our PE 2016.1.2 Infrastructure. It looks like the service puppet is not managed on a node if we apply pupept_agent. It looks like puppet_agent ist not including the service definitions in pe:

``` puppet
    # On windows, our MSI handles the services
    # On PE AIO nodes, PE Agent nodegroup is managing the services
    if $::osfamily != 'windows' and (!is_pe or versioncmp($::clientversion, '4.0.0') < 0) {
      class { '::puppet_agent::service':
        require => Class['::puppet_agent::install'],
      }
```

I've reviewed the classes of "PE Agent nodegroup" and none of them is managing the puppet agent service (mcollective and pxp-agent are managed thogh). Would it be possible to manage the puppet agent service with this module on a pe infradtructure as well?

Regards

Raskil

**Comment by MikaelSmith** [comment]
@highb do you remember why it's coded that way? I thought it was to avoid conflict in the PE modules, but I can't find code managing the `puppet` service either.

**Comment by highb** [comment]
@MikaelSmith Yeah, I think it's because the windows install script that the `puppet_agent` module runs also attempts to manage the service and we didn't want those to conflict with each other.

**Comment by geoffnichols** [comment]
This issue has not been updated in some time and is now being closed due to inactivity. This isn’t necessarily a statement that this issue isn’t important - other issues may have demanded precedence since it was filed, or it may have simply slipped through the cracks. If any viewer/watcher feels closing this ticket is an error, please open a new issue at our JIRA tracker at https://tickets.puppetlabs.com/browse/MODULES. Our apologies in advance for any mistake on this.

**Comment by kenyon** [comment]
I found this issue while researching how to properly manage the puppet service under Puppet Enterprise. As far as I can tell, this issue is still valid, there doesn't seem to be an official way to manage the puppet service with puppet on PE. The same observation was made here: https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/461#issuecomment-1155731041
