### ISSUE TITLE
Windows agent version not detected, agent installation on every puppet run

### ISSUE THREAD

**Issue by sjlanu** [puppetlabs/puppetlabs-puppet_agent#221]
Installation of Windows puppet agent occurs on every puppet agent run, even if installed agent is already same version as declared in $package_version.

Workaround for me was to add _if $::aio_agent_version < '$package_version'_ in line 17 of windows/install.pp

**Comment by MikaelSmith** [comment]
What system are you on? That's odd, I thought we tested that scenario.

**Comment by sjlanu** [comment]
Windows 10 1607

**Comment by smortex** [comment]
With an up-to-date puppet_agent module  (1.3.2), an up-to-date Puppet Master (4.9.4, not installed with the AIO package), and Puppet Agent installed with the AIO package on a Windows machines (Windows 10 Home 14393 and Windows 7 7601) with the following manifest:

```
  class { '::puppet_agent':
    package_version => '1.9.3',
  }
```

each agent generates a new `install_puppet.bat` script and execute it (the script contains timestamps so it changes at each run):

```
ruby 2.1.9p490 (2016-03-30 revision 54437) [x64-mingw32]

C:\WINDOWS\system32>puppet --version
4.9.4

C:\WINDOWS\system32>puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for my.node.has.a.funny.name
Info: Applying configuration version 'c97154c250f6d4ba1c61180a0afd22c994ebdb35'
Notice: /Stage[main]/Puppet_agent::Windows::Install/File[C:\Users\Romain\AppData\Local\Temp\install_puppet.bat]/content:

Notice: /Stage[main]/Puppet_agent::Windows::Install/File[C:\Users\Romain\AppData\Local\Temp\install_puppet.bat]/content: content changed '{md5}4b68bfb53cf121cd163ec1ade98e294c' to '{md5}ed97c0d5afdd82f510c88a0816d1c171'
Notice: /Stage[main]/Puppet_agent::Windows::Install/Exec[install_puppet.bat]/returns: executed successfully
Notice: /Stage[main]/Puppet_agent::Windows::Install/Exec[fix inheritable SYSTEM perms]/returns: executed successfully
Notice: Applied catalog in 3.02 seconds

C:\WINDOWS\system32>
```

This seems to be caused by the first part of the test at https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/be4f2958ab9e6489ffe50f440cf63f1e51146a11/manifests/init.pp#L88 : I am not using Puppet Enterprise and `${_expected_package_version}` is set to `${package_version}`.

I guess that using PE or not, we should only consider an update is required if AIO is not installed or if the installed version does not match the desired version?

@sjlanu does this message rings a bell regarding to your setup and the issue you are facing ?

**Comment by sjlanu** [comment]
Yes, this is exactly the issue and we have same versions of puppet master and puppet agent.

**Comment by jordigg** [comment]
We have the same issue as well

**Comment by geoffnichols** [comment]
Thank you for opening this. We're migrating this project's Github issues into our JIRA tracker. For updates on this issue, please follow https://tickets.puppetlabs.com/browse/MODULES-4991.
