### ISSUE TITLE
How to add custom puppet master server

### ISSUE THREAD

**Issue by es1o** [puppetlabs/puppetlabs-puppet_agent#222]
Hello,
I've a puppet server with different dns name than puppet with default domain.

I used my own puppet module and I modified puppet.conf file and add custom server name. Could I do that with this module? If yes, how?

Thanks

**Comment by MikaelSmith** [comment]
That's not currently managed with this module. It's an improvement I think we'd like to see.

**Comment by geoffnichols** [comment]
Thank you for filing this issue. We agree it is likely an improvement, but due to other issues demanding precedence, we don’t anticipate being able to address this any time soon. As such we are closing this for now. We may revisit it at a later time, and if so will open an issue in our JIRA tracker at https://tickets.puppetlabs.com/browse/MODULES.
